version: '3'
services:
  web:
    build: .
    volumes:
      - .:/www/app
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "5000:80"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
